#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : progress
Version  : 1.5
Release  : 17
URL      : https://files.pythonhosted.org/packages/38/ef/2e887b3d2b248916fc2121889ce68af8a16aaddbe82f9ae6533c24ff0d2b/progress-1.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/38/ef/2e887b3d2b248916fc2121889ce68af8a16aaddbe82f9ae6533c24ff0d2b/progress-1.5.tar.gz
Summary  : Easy to use progress bars
Group    : Development/Tools
License  : ISC
Requires: progress-python = %{version}-%{release}
Requires: progress-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
==================================
        
        |pypi|
        
        |demo|

%package python
Summary: python components for the progress package.
Group: Default
Requires: progress-python3 = %{version}-%{release}

%description python
python components for the progress package.


%package python3
Summary: python3 components for the progress package.
Group: Default
Requires: python3-core
Provides: pypi(progress)

%description python3
python3 components for the progress package.


%prep
%setup -q -n progress-1.5
cd %{_builddir}/progress-1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618931918
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
